apiVersion: v1
kind: Namespace
metadata:
  name: wonderfood

---

apiVersion: v1
kind: Secret
metadata:
  name: database-connection-secret
  namespace: wonderfood
type: Opaque
data:
  connectionstring: ${{ secrets.CONNECTION_STRING }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wonderfood-app
  namespace: wonderfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wonderfood-app
  template:
    metadata:
      labels:
        app: wonderfood-app
    spec:
      containers:
        - name: wonderfood-app
          image: 381491872338.dkr.ecr.us-east-1.amazonaws.com/wdf-ecr:latest
          ports:
            - containerPort: 80
              name: wonderfood-app
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          env:
            - name: ConnectionString
              valueFrom:
                secretKeyRef:
                  name: database-connection-secret
                  key: connectionstring

---

apiVersion: v1
kind: Service
metadata:
  name: wonderfood-app-service
  namespace: wonderfood
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: wonderfood-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wonderfood-app-hpa
  namespace: wonderfood
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wonderfood-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70