
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wonderfood-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wonderfood-app
  template:
    metadata:
      labels:
        app: wonderfood-app
    spec:
      containers:
        - name: wonderfood-app
          image: wonderfoodacr.azurecr.io/wonderfood:latest
          ports:
            - containerPort: 80
              name: wonderfood-app
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          env:
            - name: ConnectionString
              value: ${{ secrets.CONNECTION_STRING }}
---

apiVersion: v1
kind: Service
metadata:
  name: wonderfood-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: wonderfood-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wonderfood-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wonderfood-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70