version: '3.8'

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      - ConnectionString=Server=sqlserver,1433;Database=master;User Id=sa;Password=senhaForte123!;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: senhaForte123!
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"