version: '3.8'

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      - ConnectionString=Server=mysql;Database=wonderfood-db;Uid=userdb;Pwd=senhaForte123!;Connect Timeout=60;

  mysql:
    image: mysql:8.0.34
    container_name: wonderfood-mysql
    environment:
      MYSQL_ROOT_PASSWORD: senhaForte123!
      MYSQL_DATABASE: wonderfood-db
      MYSQL_USER: userdb
      MYSQL_PASSWORD: senhaForte123!
    ports:
      - "3306:3306"
    #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci