name: CI Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Efetua Login no Azure
        uses: Azure/login@v1.6.1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
                
      - name: Instalação do .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - name: Restaura as dependências do projeto
        run:
          dotnet restore

      - name: Build da aplicação
        run:
          dotnet build --configuration Release

      - name: Executa Testes Unitários
        run:
          dotnet test --no-build --configuration Release --verbosity normal

      - name: Login no DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build, Tag e Push da Imagem para o DockerHub
        run: |
          docker build -t felipefabricio/wonderfood:latest -f Dockerfile .
          docker push felipefabricio/wonderfood:latest               