name: CI-CD

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.29.1'
        id: install
            
      - name: Azure Login
        uses: Azure/login@v1.6.1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            6.0.x
            7.0.x

      - name: Restore packages 
        run: 
          dotnet restore
         
      - name: Build application
        run: 
          dotnet build --configuration Release
      
      - name: Run tests
        run: 
          dotnet test --no-build --configuration Release --verbosity normal

      - name: Login Azure Container Registry
        run: az acr login --name wonderfoodacr

      - name: Build, Tag e Push da Imagem para o Azure Container Registry
        run: |
          docker build -t wonderfoodacr.azurecr.io/wonderfood:latest -f Dockerfile .
          docker push wonderfoodacr.azurecr.io/wonderfood:latest
          
      - name: Setar Contexto K8S
        run: az aks get-credentials --resource-group wonderfood-rg --name wonderfood-cluster
        
      - name: Deploy to Kubernetes
        run: |
          kubectl config set-context --current --namespace=wonderfood
          kubectl create secret generic mysql-connection-secret \
            --dry-run=client \
            --from-literal=connectionString='${{ secrets.CONNECTION_STRING }}'
          kubectl apply -f deployment.yml
          
          
